### PR TITLE
Fix destroying lock instance

### LINKED ISSUE #907: Unable to destroy Lock instance
Hey guys,

I see this error when I call `lock.destroy()`:

```js
Uncaught TypeError: Cannot read property 'getIn' of undefined
    at http://localhost:3001/assets/vendors.js:16215:15
    at getUIAttribute (http://localhost:3001/assets/vendors.js:7967:10)
    at Object.avatar (http://localhost:3001/assets/vendors.js:7984:12)
    at http://localhost:3001/assets/vendors.js:6961:25
    at Object.render-1 (http://localhost:3001/assets/vendors.js:12553:20)
    at http://localhost:3001/assets/vendors.js:15998:24
    at Array.forEach (native)
    at Atom._change (http://localhost:3001/assets/vendors.js:15997:26)
    at Atom.swap (http://localhost:3001/assets/vendors.js:15969:17)
    at swap (http://localhost:3001/assets/vendors.js:12566:21)
    at removeLock (http://localhost:3001/assets/vendors.js:7289:19)
    at Auth0Lock.destroy (http://localhost:3001/assets/vendors.js:7061:29)
    at Auth0Lock.<anonymous> (http://localhost:3001/assets/client.js:35:12)
    at Auth0Lock../node_modules/events/events.js.EventEmitter.emit (http://localhost:3001/assets/vendors.js:31155:17)
    at http://localhost:3001/assets/vendors.js:8337:35
```

### PR DESCRIPTION
**Pull request by luisrudge**
fix #907, https://github.com/auth0/lock/issues/1090, https://github.com/auth0/lock/pull/1091

### Changes

This is a copy of https://github.com/auth0/lock/pull/1091, but I couldn't rebase because the original branch was removed.

This fixes a case where lock couldn't be destroyed `lock.destroy()`.

### CODE REVIEW

File: src/store/index.js [hunk 1]
```diff
@@ -7,7 +7,9 @@ export function observe(key, id, f) {
   subscribe(`${key}-${id}`, (_, oldState, newState) => {
     const m = getEntity(newState, 'lock', id);
     const oldM = getEntity(oldState, 'lock', id);
-    if (m != oldM) f(m);
+    if (m && !m.equals(oldM)) {
```
Comment (damieng) [inline src/store/index.js]: Perhaps (m != null) would be safer?  What types does getEntity return?

Comment (luisrudge) [reply src/store/index.js]: they will always be different because `m` is an immutable object (which is a new reference, so will always be false if you compare with !=). that's why the fix is actually use `.equals`, which is an immutable method.
